# Generated by Django 4.1.1 on 2022-09-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=80)),
                ('destinário', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('observacao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
